<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductInController;
use App\Http\Controllers\ProductOutController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\Auth\AuthenticatedSessionController; // Add this line
use App\Http\Controllers\DashboardController;

// Redirect to login by default
Route::get('/', function () {
    return redirect()->route('login');
});

// Dashboard Route
Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard')->middleware('auth');

// Product Routes
Route::resource('products', ProductController::class)->middleware('auth');

// ProductIn Routes (Stock In)
Route::resource('productins', ProductInController::class)->middleware('auth');

// ProductOut Routes (Stock Out)
Route::resource('productouts', ProductOutController::class)->middleware('auth');

// Reports Route
Route::get('reports', [ReportController::class, 'index'])->name('reports.index')->middleware('auth');

// Logout Route
Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');

// Authentication Routes (generated by Laravel Breeze or similar)
require __DIR__.'/auth.php';

Route::delete('/products/{ProductCode}', [ProductController::class, 'destroy'])->name('products.destroy');
