<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductInController;
use App\Http\Controllers\ProductOutController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\Auth\AuthenticatedSessionController; // Add this line
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;

// Redirect to index page  by default
Route::get('/', function () {
    return view('index');
});
// this is route for Log in
Route::get('/login', function () {
    return redirect()->route('login');
});

// Dashboard Route
Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard')->middleware('auth');

// Add these profile routes
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    // Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    // Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// Product Routes
Route::resource('products', ProductController::class)->middleware('auth');

// ProductIn Routes (Stock In) with all functionality
Route::resource('productins', ProductInController::class)->middleware('auth');

// ProductOut Routes (Stock Out) with all functionality
Route::resource('productouts', ProductOutController::class)->middleware('auth');

// Reports Route
Route::get('reports', [ReportController::class, 'index'])->name('reports.index')->middleware('auth');

// Logout Route
Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');

// Authentication Routes (generated by Laravel Breeze or similar)
require __DIR__.'/auth.php';

Route::delete('/products/{ProductCode}', [ProductController::class, 'destroy'])->name('products.destroy');
